stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: normal
  IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/mysql-slave-sync

before_script:
  - . .gitlab-ci-functions/docker.sh
  - . .gitlab-ci-functions/kubernetes.sh
  - registry_login
  - helm_cluster_login
  - KUBECTL="kubectl --server=$KUBE_SERVER --token=$KUBE_TOKEN"

after_script:
  - . .gitlab-ci-functions/kubernetes.sh 
  - helm_cluster_logout

build:
  tags:
    - dev
  stage: build
  script:
    - envsubst < .env.example > .env
    - docker build -t $IMAGE:$CI_PIPELINE_ID .
    - docker push $IMAGE:$CI_PIPELINE_ID
  
deploy:
  tags:
    - dev
  stage: deploy
  script:
    - namespace_secret_additional_project_registry mysql-slave-sync pipeline_bot_registry $PIPELINE_BOT_TOKEN_REGISTRY
    - |
      $HELM \
          upgrade \
          --atomic \
          --debug \
          --wait \
          --namespace ${KUBE_NAMESPACE} \
          --install ${KUBE_NAMESPACE} \
          .helm/ \
          --set image.repository=$IMAGE \
          --set image.tag=$CI_PIPELINE_ID