apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    metadata/deployed-by: {{ .Values.metadata.deployedBy | quote }}
    metadata/pipline-url: {{ .Values.metadata.piplineUrl | quote }}
spec:
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  schedule: {{ .Values.cron.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cron.backoffLimit }}
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Chart.Name }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          imagePullSecrets:
            - name: {{ .Values.image.pullSecret }}
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}-app
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}